### PR TITLE
NOPS-681 Add clean step into stop/restart

### PR DESCRIPTION
**Pull request by mkostrikin**
Handsome hack to make docker containers run again.

@diogokiss @tnn

### CODE REVIEW

**Comment by diogokiss** [comment]
💋  Good!

**Comment by JesperTerkelsen** [comment]
:+1:

**Comment by tnn** [comment]
@mkostrikin Should we upstream this?

**Comment by mkostrikin** [comment]
@tnn this too handsome patch to upstream.
But I will think about that.

**Pull request merged**
